# Generated by Django 3.1.4 on 2020-12-11 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bikes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=25)),
                ('model', models.CharField(max_length=25)),
                ('image', models.ImageField(upload_to='bike_images')),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
