# Generated by Django 3.1.4 on 2020-12-08 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motorbike_shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bikes',
            name='image',
            field=models.ImageField(upload_to='static/images'),
        ),
    ]
