# Generated by Django 3.1.4 on 2020-12-09 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motorbike_shop', '0002_auto_20201208_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bikes',
            name='image',
            field=models.ImageField(upload_to='bike_images'),
        ),
    ]
