# Generated by Django 3.1.2 on 2020-10-29 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='text',
        ),
    ]
