# Generated by Django 3.1.1 on 2020-09-24 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_django_project', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Game',
        ),
    ]
